### ISSUE TITLE
Got this error when i use the latest

### ISSUE THREAD

**Issue by jeraldpunx** [MotazSabri/Hanami-release#18]
![image](https://github.com/MotazSabri/Hanami-release/assets/5249781/85e930d6-9d23-4316-ba88-7b9050d77aac)

**Comment by MotazSabri** [comment]
@jeraldpunx 
Thanks a lot for reporting the bug. I created a new hotfix for this issue.
Do you mind downloading the new version and confirming the fix?

I appreciate your feedback, Thanks

**Comment by jeraldpunx** [comment]
here is the new version, only one hanami instance but got error.
![image](https://github.com/MotazSabri/Hanami-release/assets/5249781/f4859c10-e4d4-47bf-b5fc-83429d0f7c0b)

**Comment by MotazSabri** [comment]
The application forks smaller apps while operating to ensure robust performance. 

The shutting down takes few seconds (to minutes), especially if the shutdown happens abruptly.
 Have you uninstalled the olde version and installed the new version?  

Sorry if the questions are naive, i am trying to check the context of the issue.

**Comment by jeraldpunx** [comment]
tried uninstall, then restart pc, and install then open... still same error

**Comment by MotazSabri** [comment]
Thanks for describing the situation, @jeraldpunx . This seems to be related to your machine configuration. We need to debug this by observing the logs.

1. Install this custom version of [Hanami](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release2.0/Hanami.Installer.Debug.exe) (The link will be removed after this issue is resolved), This version allows logging all events and errors in details. Do not run the application yet.
1. Go to the Windows TEMP folder (By clicking WINDOWS + R and then type %temp% and enter) and find a folder called HanamiApp.
2. The file contains the operational contents, delete everything in it (To avoid sharing any personal details) then run the Hanami application.
3. After a while of running the app (Seconds), in the HanamiApp folder, you will find a file called Traces.log. In it, we may find clues as to why this issue happened.
4. If it's a thing you can not manage by yourself, please share the traces.log here so I can try debugging it.
5.

**Comment by jeraldpunx** [comment]
Hello, i've got same error after this steps. and here is the traces.log
[Traces.log](https://github.com/user-attachments/files/15597733/Traces.log)

**Comment by MotazSabri** [comment]
Thank you for your data preparation. It appears that the problem might be occurring within the new GPT component on your side. When the application crashes, it should display more messages if the issue originates within the application itself. However, it seems like the issue might be external, possibly related to a firewall or access permissions.

Do you have rules in your network that prevent access to OpenAI or any GPT service provider?

Could you please try [this version](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release2.0/Hanami.Installer.Debug.exe)? It has enhanced logging to capture more external errors, if any.

Thanks for your help and looking forward to hearing from you!

**Comment by jeraldpunx** [comment]
here is the new traces.log... what i did is uninstall -> remove hanami on %temp% -> install that new installer then got  this traces.log
[Traces.log](https://github.com/user-attachments/files/15613577/Traces.log)

**Comment by jeraldpunx** [comment]
it can open now, but didn't translate it. 
![image](https://github.com/MotazSabri/Hanami-release/assets/5249781/2fe71e39-cf23-4158-80d8-661e097f21b2)

here is the new traces.log (i just cut other lines "new chunk" cause it pass 25mb limit)
[Traces.log](https://github.com/user-attachments/files/15688307/Traces.log)

**Comment by MotazSabri** [comment]
Thanks, I can see the error source now in the logs. it is referenced by 

`
Error 0x8889000a
`

that suggests an issue related to the audio endpoint device. This could be due to several reasons, such as permissions, device availability, or compatibility issues.

Try [this version ](https://github.com/MotazSabri/Hanami-release/releases/download/Hanami-release2.0/Hanami.Installer.Debug.exe)and apply the following Solutions:

1. Test with Different Devices:
If possible, test with a different speaker to see if the issue is specific to the current device. 

2. Check Device Availability:
Ensure that the device is available and not being used by another application.

3. Verify Permissions:
Make sure that your application has the necessary permissions to access the audio devices. This may involve adjusting system settings or running your application with elevated permissions.

4. Update Drivers:
Ensure that your audio drivers are up to date, as outdated drivers can cause compatibility issues.
 
5. Check for Configuration Changes:
Verify if any recent changes have been made to the audio configuration, such as disabling devices or modifying settings that could affect access.

Looking forward to hearing from you.

**Comment by jeraldpunx** [comment]
btw it's working now on this new version

**Comment by MotazSabri** [comment]
> btw it's working now on this new version

Thanks for confirming.
