### ISSUE TITLE
What requirements?

### ISSUE THREAD

**Issue by rusboard** [MotazSabri/Hanami-release#2]
Hello,
any requirements for this project? Maybe Win10 only, or something.

I have win11 and can't run program, it gives error.

![image](https://user-images.githubusercontent.com/5380762/232728943-b9c630db-a24f-44eb-9c17-65fb0c8cd194.png)

**Comment by rusboard** [comment]
hm... After close this message I click on the shortcut on the desktop and all ok now.
interesting.

**Comment by rusboard** [comment]
But now another problem

![image](https://user-images.githubusercontent.com/5380762/232730075-41f6db06-4705-4789-b741-c353382bf27f.png)

No audio signal, I tried every speaker that I have, mic, speakers, etc.
Any idea?

**Comment by rusboard** [comment]
Ok, another piece of information.

When I just open an application by default it's Speakers and it's translating movies for example.
But If  I will choose a Microphone then the translation doesn't work. And if I will switch back to Speakers again translation will not work too.

**Comment by MotazSabri** [comment]
> hm... After close this message I click on the shortcut on the desktop and all ok now. interesting.

Thanks for your kind remark.

The App first run tends to require a bit of resources to prepare its directory structure and check connections with translation and transcriptions APIs. Therefore, giving a loading time may be required. We hope this issue is not happening again with you. Let me know if it is still happening.
